[package]
name = "imaudio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.0"
lame = "0.1.3"
mp3lame-encoder = "0.1.4"
puremp3 = "0.1.0"
wav = "1.0.0"
